<a href="https://colab.research.google.com/github/crodriguezbay/MLforMkting/blob/main/EjemploTrivialTFIDF.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# TF-IDF Vectorization Function

In [1]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer

The function `calculate_tfidf_vectors` takes three lists of words (tokenized vectors) as input. It combines them to form a corpus, then uses `TfidfVectorizer` to fit and transform this corpus into TF-IDF representations. Finally, it returns the individual TF-IDF vectors for each of the original inputs.

In [2]:
def calculate_tfidf_vectors(vector1, vector2, vector3):
    """
    Calculates the TF-IDF vectors for three given tokenized word vectors.

    Args:
        vector1 (list of str): The first list of words (tokenized).
        vector2 (list of str): The second list of words (tokenized).
        vector3 (list of str): The third list of words (tokenized).

    Returns:
        tuple: A tuple containing the TF-IDF vectors for vector1, vector2, and vector3.
    """
    # Join words in each vector to form a document string
    doc1 = ' '.join(vector1)
    doc2 = ' '.join(vector2)
    doc3 = ' '.join(vector3)

    # Create a corpus from the three documents
    corpus = [doc1, doc2, doc3]

    # Initialize TfidfVectorizer
    vectorizer = TfidfVectorizer()

    # Fit the vectorizer to the corpus and transform the documents
    tfidf_matrix = vectorizer.fit_transform(corpus)

    # Get the feature names (words) to make the output readable
    feature_names = vectorizer.get_feature_names_out()

    # Convert the TF-IDF matrix rows to DataFrames for easier viewing
    tfidf_vector1 = pd.DataFrame(tfidf_matrix[0].T.todense(), index=feature_names, columns=['TF-IDF Vector 1'])
    tfidf_vector2 = pd.DataFrame(tfidf_matrix[1].T.todense(), index=feature_names, columns=['TF-IDF Vector 2'])
    tfidf_vector3 = pd.DataFrame(tfidf_matrix[2].T.todense(), index=feature_names, columns=['TF-IDF Vector 3'])

    return tfidf_vector1, tfidf_vector2, tfidf_vector3

### Example Usage

In [3]:
# Define sample tokenized word vectors
sample_vector1 = ['este', 'es', 'el', 'primer', 'documento', 'de', 'ejemplo']
sample_vector2 = ['el', 'segundo', 'documento', 'tiene', 'palabras', 'diferentes']
sample_vector3 = ['este', 'es', 'un', 'tercer', 'documento', 'tambien', 'de', 'ejemplo']

# Calculate TF-IDF vectors
tfidf_v1, tfidf_v2, tfidf_v3 = calculate_tfidf_vectors(sample_vector1, sample_vector2, sample_vector3)

# Display the results
print("TF-IDF Vector 1:")
display(tfidf_v1.sort_values(by='TF-IDF Vector 1', ascending=False))

print("\nTF-IDF Vector 2:")
display(tfidf_v2.sort_values(by='TF-IDF Vector 2', ascending=False))

print("\nTF-IDF Vector 3:")
display(tfidf_v3.sort_values(by='TF-IDF Vector 3', ascending=False))

TF-IDF Vector 1:

            TF-IDF Vector 1
primer             0.485596
de                 0.369308
es                 0.369308
el                 0.369308
este               0.369308
ejemplo            0.369308
documento          0.286801
diferentes         0.000000
palabras           0.000000
segundo            0.000000
tambien            0.000000
tercer             0.000000
tiene              0.000000
un                 0.000000

TF-IDF Vector 2:

            TF-IDF Vector 2
diferentes         0.450504
palabras           0.450504
segundo            0.450504
tiene              0.450504
el                 0.342620
documento          0.266075
es                 0.000000
ejemplo            0.000000
de                 0.000000
este               0.000000
primer             0.000000
tambien            0.000000
tercer             0.000000
un                 0.000000

TF-IDF Vector 3:

            TF-IDF Vector 3
un                 0.420241
tercer             0.420241
tambien            0.420241
es                 0.319604
de                 0.319604
ejemplo            0.319604
este               0.319604
documento          0.248201
el                 0.000000
diferentes         0.000000
segundo            0.000000
primer             0.000000
palabras           0.000000
tiene              0.000000

In [4]:
vector1=['gatos', 'casa']
vector2=['perros', 'casa', 'afuera']
vector3=['gatos', 'perros', 'amigos']

v1, v2, v3 = calculate_tfidf_vectors(vector1, vector2, vector3)

display(v1)
display(v2)
display(v3)

        TF-IDF Vector 1
afuera         0.000000
amigos         0.000000
casa           0.707107
gatos          0.707107
perros         0.000000

        TF-IDF Vector 2
afuera         0.680919
amigos         0.000000
casa           0.517856
gatos          0.000000
perros         0.517856

        TF-IDF Vector 3
afuera         0.000000
amigos         0.680919
casa           0.000000
gatos          0.517856
perros         0.517856